# Generated by Django 4.2.7 on 2023-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.CharField(default='data', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
