# Generated by Django 4.2.7 on 2023-11-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finweb', '0002_remove_category_subcategory_category_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('service_id', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='service_logo')),
            ],
        ),
    ]
