# Generated by Django 4.2.7 on 2023-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finweb', '0003_networkservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkservice',
            name='service_id',
            field=models.CharField(max_length=20),
        ),
    ]
