# Generated by Django 4.2.7 on 2023-11-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finweb', '0004_alter_networkservice_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finweb.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkservice',
            name='service_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='networkservice',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
    ]
